# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

# Grant the minimum permissions needed to push and publish
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Grab your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Prepare docs/ as the exact site root
      - name: Prepare docs folder
        run: |
          # clear previous run
          rm -rf docs
          mkdir docs

          # copy all your static pages & assets
          cp index.html planner.html docs/
          cp -r css images docs/    || true

          # inject real Maps key into service.html
          sed "s|__MAP_KEY__|${{ secrets.GOOGLE_MAPS_API_KEY }}|g" \
            service.template.html > docs/service.html

      # 3) Tell GitHub we’re doing a Pages deploy
      - name: Configure Pages
        uses: actions/configure-pages@v2

      # 4) Upload everything under docs/ as the build artifact
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      # 5) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          publish_dir: docs # this is the directory we prepared above     