name: Build & Deploy to GitHub Pages

permissions:
  contents: read    # allow reading the repo
  pages: write      # allow publishing to GitHub Pages
  id-token: write   # required by configure-pages

on:
  push:
    branches: [ main ]  # change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v3

      # 2. Prepare the docs/ folder for deployment
      - name: Prepare docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp index.html planner.html docs/
          cp -r css images docs/ || true
          sed "s|__MAP_KEY__|${{ secrets.GOOGLE_MAPS_API_KEY }}|g" \
            service.template.html > docs/service.html

      # 3. Configure GitHub Pages to use Actions
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # 4. Upload docs/ as the Pages artifact
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      # 5. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
